### ISSUE TITLE
No Mailbox to select

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/happiness-reports-for-help-scout#2]
I don't see any mailbox after entering my API keys: (deleted)

**Comment by amdrew** [comment]
@pippinsplugins stop breaking stuff please

**Comment by amdrew** [comment]
@pippinsplugins Pull down latest and give it another go, should be fixed now

**Comment by worldtravlr** [comment]
This is working for me now. (API Key deleted for security reasons :-)

![screen shot 2015-10-29 at 7 48 14 am](https://cloud.githubusercontent.com/assets/6686642/10820158/77e25cdc-7e11-11e5-9d05-a223bda5aca5.jpg)

**Comment by amdrew** [comment]
Should be working now
