### ISSUE TITLE
Add graphs

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/happiness-reports-for-help-scout#3]
The shortcode could have a "graph" option that shows a graph for each rating, just like Help Scout

**Comment by amdrew** [comment]
So far on 2015 theme (they also animate)

![screen shot 2015-10-23 at 8 27 10 pm](https://cloud.githubusercontent.com/assets/52581/10686821/78a1d6c6-79c4-11e5-9765-01f6353b369c.png)

**Comment by worldtravlr** [comment]
This is awesome @sumobi!  I was just asking Help Ccout about a month ago if they had this capability/option for wordpress.  Very cool!  Thanks for making it and love the animated graph circles!  I have implements it on our contact page here - https://5daydeal.com/contact/ :+1:

**Comment by amdrew** [comment]
@worldtravlr glad you like it! Hoping to get the graphs in soon, not too much more to do.

**Comment by worldtravlr** [comment]
Cool!  Excited to check them out :-)

**Comment by pippinsplugins** [comment]
Definitely want graphs :)

**Comment by amdrew** [comment]
Done via https://github.com/sumobi/happiness-reports-for-help-scout/commit/4c8f6a043fecd51691ef6d1326e0b5f8d8d95823

Shortcode instructions here:
https://github.com/sumobi/happiness-reports-for-help-scout/blob/master/includes/class-shortcodes.php#L10-L35

**Comment by worldtravlr** [comment]
Awesome! :+1:

**Comment by worldtravlr** [comment]
This update does not seems to work on my setup even without the graphs.  I have a test page here - https://5daydeal.com/?p=52306

Any ideas?  Can I help provide some more info to troubleshoot?  I am using Divi theme, but was not using the builder for this page.

Using the following text for the page:

[happiness_report]

Show all ratings (great, okay, not good) as an unordered list

[happiness_report rating="great"]

Show only the "great" rating

[happiness_report rating="okay"]

Show only the "okay" rating

[happiness_report rating="not good"]

Show only the "not good" ratings

[happiness_report graph="yes"]

Show all ratings (great, okay, not good) as individual graphs

[happiness_report rating="great" graph="yes"]

Show only the "great" rating as a graph

[happiness_report rating="okay" graph="yes"]

Show only the "okay" rating as a graph

[happiness_report rating="not good" graph="yes"]

Show only the "not good" rating as a graph

**Comment by amdrew** [comment]
@worldtravlr Does deleting the plugin and re-installing help? The plugin name changed, as did the options row in the database, transient names and a few other things. It could be stuck somehow. MIght even just need a re-save from the settings page.

**Comment by worldtravlr** [comment]
@sumobi Thanks!  Worked like a charm :-)  Looks like maybe the API was lost in the update.  Relatedly, can I recommend adding a "Settings" Link in the plugin area?  Like many wordpress plugins have:

Settings | Deactivate | Edit

So that is is more intuitive what to do and where to go once installed.  Awesome work and thanks again!  Love the graphs and will probably add to contact page soon :-)

**Comment by amdrew** [comment]
@worldtravlr You're welcome. Oh yes, definitely need that :) Will be uploading to the WP repo today or tomorrow so you can grab the official version soon.

**Comment by amdrew** [comment]
official version here: https://wordpress.org/plugins/happiness-reports-for-help-scout/ (with settings link)

**Comment by worldtravlr** [comment]
Awesome!  Thanks again @sumobi!
