### ISSUE TITLE
[happiness_report] Short Code Not Working

### ISSUE THREAD

**Issue by worldtravlr** [easydigitaldownloads/happiness-reports-for-help-scout#5]
This is probably a plugin conflict or something specific to my system maybe, but thought I would mention it in case it is an actual issue.

I can get the individual short codes to work without issue: 
[happiness_report rating="great"]
[happiness_report rating="okay"]
[happiness_report rating="not good"]

But when I try to use just the main shortcode - [happiness_report] - nothing is shown or seen.  Not sure if maybe that shortcode is not active yet or if there is an issue, but thought I would mention it.  Let me know if you want me to link to a demo page with the issues or show a console report.

**Comment by amdrew** [comment]
@worldtravlr At the moment the shortcode by itself doesn't do anything, you need to pass in the rating. I'm considering making it so if you leave off the rating it shows all ratings together. My thought were that passing in a rating would be ideal since you might like to only show the great rating.

**Comment by worldtravlr** [comment]
Ah.  That makes perfect sense.  As there is no documentation on what they do, I just assumed incorrectly that the [happiness_report] by itself would show all.  Make sense to have them separate and not sure the [happiness_report] need to do anything by itself, but might be more initiative if not to much extra code/work.  I think it is fine either way and a really cool plugin!

**Comment by pippinsplugins** [comment]
If no rating is specified, I think it should show an unordered list of each rating level and the percentage for it.

**Comment by pippinsplugins** [comment]
- Great: 83%
- Okay: 15%
- Bad: 2%

**Comment by amdrew** [comment]
@pippinsplugins I like that idea
