### ISSUE TITLE
Clear hs_happiness_report_ratings transient when settings are saved

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/happiness-reports-for-help-scout#6]
The happiness report retrieved from the API is stored in a transient `hs_happiness_report_ratings`. This should be deleted when settings are saved so that if the site admin adds/removes mailboxes from the settings, the score shown on the frontend immediately reflects the change.

**Comment by pippinsplugins** [comment]
Looks like this is designed to already be done but only happens when the date range is changed. I'd propose that it always be cleared.

**Comment by amdrew** [comment]
@pippinsplugins good point, only set it up so that it cleared the transient when date changes but of course the other settings might also change the data, such as changing the mailboxes.
